### ISSUE TITLE
Remove harcoded page number

### ISSUE THREAD

**Issue by t13ka** [VirtoCommerce/vc-odt-mpa-theme#127]
We have a file with accumulated constants:
![image](https://user-images.githubusercontent.com/12604378/82524701-c9e76080-9b59-11ea-91b1-5ef9b5499a34.png)

also, we have hardcoded page numbers in files, eg:
![image](https://user-images.githubusercontent.com/12604378/82524779-01560d00-9b5a-11ea-9cef-3604f4f603f5.png)

we should replace hardcoded page numbers with our constant values

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2441 has been created
