### ISSUE TITLE
Reduce code implicitness

### ISSUE THREAD

**Issue by t13ka** [VirtoCommerce/vc-odt-mpa-theme#128]
As we know the Typescript allow us to use modifications in methods and explicitly define the return type value,
so I'd like to offer you set all modifications and value types (in all typescript files):
![image](https://user-images.githubusercontent.com/12604378/82525647-1338af80-9b5c-11ea-9cc4-23de74155966.png)

It should make your code more clear and improve maintainability

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2442 has been created
