### ISSUE TITLE
The "unmounted" method does not exist in Vue lifecycle hooks

### ISSUE THREAD

**Issue by artmakarov** [VirtoCommerce/vc-odt-mpa-theme#134]
Replace "unmounted" method with "beforeDestroy" method
https://github.com/VirtoCommerce/vc-odt-mpa-theme/blob/e605306dbbbfb7a445e5ab0bd19b349737b72ef9/client-app/src/libs/error-handling/components/error-info.vue#L71-L73

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-3404 has been created
