### ISSUE TITLE
Issue with "npm run dev" command

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-odt-mpa-theme#170]
When I run npm run dev command, I am getting the below error.

![image](https://user-images.githubusercontent.com/71070755/102806106-4ab55600-43e2-11eb-9f36-3ed3de1eb5b0.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6467 has been created

**Comment by OlegoO** [comment]
The correct command 
```
npm run build:dev
```

Here list of the command:
https://github.com/VirtoCommerce/vc-odt-mpa-theme/blob/dev/client-app/package.json#L6-L14

We updated the documentation.
